# Site settings
title: "Ted Li"
email: lizhen@outlook.jp
description: "码农"
baseurl: ""
url: "https://tedli.github.io/"
title_description: "程序猿"
title_image: "http://www.91feizhuliu.com/uploads/4b7bc60ec643b45e/16.jpg"
google_analytics: "UA-85063279-1"
disqus_account: cartenoire
github_repository: https://github.com/tedli
addthis_id: ra-57f102bcceba7a67
post_limit: 5

# Social usernames/URLs
github_username:  tedli

# Footer
footer_left: "<i class=\"fa fa-heart\"></i> Thanks <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a> for the elegant theme"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
